foreground              #cdd6f4
background              #11111b
cursor                  #cdd6f4
cursor_text_color       #11111b

active_tab_foreground   #11111b
active_tab_background   #b4befe
inactive_tab_foreground #cdd6f4
inactive_tab_background #1e1e2e

active_border_color     #b4befe
inactive_border_color   #313244
bell_border_color       #3F2F72

color0      #3E3B44
color1      #3F2F72
color2      #514960
color3      #7B47AA
color4      #7B7485
color5      #BBB3BD
color6      #BBB3BD
color7      #F4EEF5
color8      #AAA7AC
color9      #543F98
color10     #6C6280
color11     #A45EE3
color12     #A59AB1
color13     #F9EEFC
color14     #F9EEFC
color15     #F4EEF5
